In [1]:
import numpy as np

In [2]:
data=np.random.randn(3,4)

In [3]:
data

array([[ 1.38709336,  0.97785791, -0.05964892,  1.61712041],
       [-1.23123474,  1.69621381,  0.21813905,  0.96804499],
       [ 3.13055183, -1.31782926, -0.31051473, -1.51115065]])

In [4]:
data*10

array([[ 13.87093356,   9.77857911,  -0.59648916,  16.17120411],
       [-12.31234737,  16.96213812,   2.1813905 ,   9.6804499 ],
       [ 31.30551825, -13.17829265,  -3.10514727, -15.11150649]])

In [6]:
data+data

array([[ 2.77418671,  1.95571582, -0.11929783,  3.23424082],
       [-2.46246947,  3.39242762,  0.4362781 ,  1.93608998],
       [ 6.26110365, -2.63565853, -0.62102945, -3.0223013 ]])

In [8]:
data.shape

(3, 4)

In [9]:
data=[1 ,2, 6 ,5, 8, 7]

In [10]:
arr1=np.array(data)

In [11]:
arr1

array([1, 2, 6, 5, 8, 7])

In [14]:
np.zeros((2,5))  # Learnt today

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
np.empty((4,5,2,2)) # Learnt today

array([[[[1.18664919e-311, 1.18664919e-311],
         [1.18667005e-311, 1.18667007e-311]],

        [[1.18666646e-311, 1.18667007e-311],
         [1.18666855e-311, 1.18667006e-311]],

        [[1.18667007e-311, 1.18667006e-311],
         [1.18664919e-311, 1.18664919e-311]],

        [[1.18667007e-311, 1.18664959e-311],
         [1.18667007e-311, 1.18666929e-311]],

        [[1.18666929e-311, 1.18664919e-311],
         [1.18666929e-311, 1.18666626e-311]]],


       [[[1.18664939e-311, 1.18664919e-311],
         [1.18666801e-311, 1.18666801e-311]],

        [[1.18666795e-311, 1.18666790e-311],
         [1.18666626e-311, 1.18666801e-311]],

        [[1.18666795e-311, 1.18666795e-311],
         [1.18666795e-311, 1.18666795e-311]],

        [[1.18666649e-311, 1.18664951e-311],
         [1.18664924e-311, 1.18666648e-311]],

        [[1.18666649e-311, 1.18666648e-311],
         [1.18666651e-311, 1.18666651e-311]]],


       [[[1.18666650e-311, 1.18666651e-311],
         [1.18666626e-311, 1.18

In [18]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr1=np.array((3,4), dtype=np.float64)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
# changing the datatype of numpy array using the astype functionality

In [27]:
arr2=arr1.astype(np.float16)

In [36]:
strarr=np.array(['sam','ram','gam'])

In [37]:
strarr.dtype

dtype('<U3')

In [39]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [40]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
arr*arr #element to element multiplication

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [42]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr_slice=arr[5:8]

In [47]:
arr_slice

array([], shape=(0, 3), dtype=float64)

In [48]:
arr=np.arange(10)

In [53]:
arr[5:8]=12

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
lst=[1,2,3,4,5,6,7,8,9]

lst[2:5]=[0,0,0] #THIS IS TTHE DISTINCTION FROM ARRAY. IN LIST YOU HAVE PASS  LIST ONLY VALUES

In [61]:
lst

[1, 2, 0, 0, 0, 6, 7, 8, 9]

In [62]:
# WAY TO COPY A PART OF ARRAY is to use arr.copy()

In [63]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [71]:
a=arr[5:8].copy()

In [69]:
a=5

In [72]:
a

array([12, 12, 12])

In [86]:
a=np.ones([2,2,3,5])

In [88]:
array1d=np.array([1, 2 , 3])

In [89]:
array1d

array([1, 2, 3])

In [91]:
array2d=np.array([[1, 2 , 3],[4,5,6]])

In [92]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
array3d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [94]:
array3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [98]:
array3d[0][1,2]

6

In [99]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
array2d[:1,:1]

array([[1]])

In [103]:
np.random.randn(2,2,3,4)

array([[[[-0.75984844, -1.54764951,  0.31030544, -0.56836336],
         [ 0.79549109,  0.00572323,  0.60034905, -0.20474614],
         [-0.45865548, -0.59732649,  0.97429362, -0.22416096]],

        [[-1.38918418,  0.09670294, -1.29383332,  1.06342416],
         [ 1.07231283,  0.23161795, -0.80100296, -0.49974594],
         [ 0.67178182, -0.90546121,  0.71656177,  1.99346713]]],


       [[[ 1.05543682,  1.26097718, -0.79894436,  0.68573917],
         [-0.07181561,  0.77937283,  0.67043799,  0.00961288],
         [ 1.72930398, -1.09585182,  0.86900813, -0.38106595]],

        [[-0.50547748, -0.6073023 , -0.49524634, -0.65341985],
         [-0.88403284, -1.33364934,  0.56828384,  1.2681073 ],
         [ 0.16691291, -1.26783602,  0.59785644, -0.52857338]]]])

In [104]:
names=np.array(['bob','cat', 'mat', 'guru', 'kit','motivation','dream'])

In [105]:
names=='bob'

array([ True, False, False, False, False, False, False])

In [106]:
data=np.random.randn(7,4)

In [111]:
data[names=='cat'][0][0]

-0.80480657494611

In [114]:
#uppose we have two arrays, the string array can be tetsed as inputting the index for the index search of another array

In [116]:
data[~(names == 'bob')]

array([[-0.80480657,  2.03878252,  0.52958465,  0.36995573],
       [-0.01686342, -0.21536533,  1.21814144,  0.43142322],
       [-0.06733   ,  1.00852894,  1.46760645, -1.75560099],
       [ 1.30817619,  0.69781662,  0.93922709, -0.80348636],
       [-0.82777666, -0.19150738,  0.04843745,  1.53698923],
       [ 0.63885741, -0.14592022,  0.39784884, -2.26122967]])

In [117]:
mask=(names=='bob') |(names=='kit')

In [119]:
data[~mask]

array([[-0.80480657,  2.03878252,  0.52958465,  0.36995573],
       [-0.01686342, -0.21536533,  1.21814144,  0.43142322],
       [-0.06733   ,  1.00852894,  1.46760645, -1.75560099],
       [-0.82777666, -0.19150738,  0.04843745,  1.53698923],
       [ 0.63885741, -0.14592022,  0.39784884, -2.26122967]])

In [120]:
data[data<0]=0

In [127]:
data[2,3]

0.43142322170568526

In [124]:
array2d

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
array2d[[0,1]] # huge observation , to acess the elements we need to
#to give just one square bracket, whereas to acess specific rows like done below use two square brackets.

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
arr=np.empty((8,4))

In [135]:
for i in range(8):
    arr[i]= i

In [139]:
arr[[-1]]

array([[7., 7., 7., 7.]])

In [144]:
arr=np.arange(32).reshape(8,4)

In [145]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [146]:
arr=np.arange(32).reshape(2,2,4,2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]]])

In [147]:
arr=np.arange(16).reshape(4,4)

In [148]:
np.dot(arr.T,arr)

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])

In [150]:
x = np.random.randn(8)

In [151]:
y = np.random.randn(8)

In [152]:
np.maximum(x,y)

array([-0.39345535,  0.46136605,  1.52949331,  0.59437477, -0.59505716,
       -0.76908764, -1.40537979,  2.59217801])

In [154]:
arr=np.random.rand(10)*7

In [155]:
arr

array([0.05028932, 4.41179328, 5.72486533, 0.14590124, 0.48871906,
       4.62093405, 5.4218179 , 1.95492063, 6.30723034, 2.6409912 ])

In [156]:
remainder,whole_part= np.modf(arr)

In [157]:
remainder

array([0.05028932, 0.41179328, 0.72486533, 0.14590124, 0.48871906,
       0.62093405, 0.4218179 , 0.95492063, 0.30723034, 0.6409912 ])

In [158]:
whole_part

array([0., 4., 5., 0., 0., 4., 5., 1., 6., 2.])